name: domus
description: A home automation smart application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility Packages
  awesome_circular_chart: ^1.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  fl_chart: ^0.65.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  geolocator: ^10.1.0
  google_sign_in: ^6.1.6
  http: ^1.2.0
  image_picker: ^0.8.4+11
  intl: ^0.18.1
  lottie: ^2.4.0
  provider: ^6.0.2
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  table_calendar: ^3.0.4

  # Firebase Core Packages
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.4.4
  firebase_messaging: ^14.9.1
  firebase_analytics: ^10.10.4

  # Firebase Web Support
  firebase_core_web: ^2.10.0
  firebase_auth_web: ^5.7.0
  cloud_firestore_web: ^3.11.0
  firebase_storage_web: ^3.7.0
  firebase_messaging_web: ^3.7.0
  firebase_analytics_web: ^0.5.5

  # JS & Web Support
  js: ^0.6.7
  web: ^0.5.0

  # SQLite dependencies
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2

  # Hive dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_1024.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/favourite.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/images/settings/
    - assets/icons/svg/
    - assets/Lottie/
    - assets/icons/menu_icons/
    - assets/images/movies/

  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        - asset: assets/fonts/ABeeZee-Regular.ttf
          style: normal
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
